//
//  FirebaseDataStructure.swift
//  Turnn
//
//  Created by Steve Cox on 8/4/16.
//  Copyright © 2016 Team Turnn. All rights reserved.
//

/*  FIREBASE DATA STRUCTURE REFERENCE
 
 (all identifiers are Strings generated by Firebase.
  in some cases we'll need to retrieve formerly created
  identifers [like when we append an event identifer to a
  user's record, etc.])
 
 Events
     - identifier
         - title: String
         - location:
             - lat: Double
             - long: Double
             - address: String
             - city: String
             - state: String
             - zip: String
         - startTime: Double
         - endTime: Double
         - categories
             - identifier: true
             - identifier: true
         - description: String
         - passwordPro: Bool
         - password: String
         - contactInfo: String
         - host: identifier (there can only be one host,
                            given how our model is set up,
                            otherwise this spot would look
                            like location & categories)
 
 Users
     - identifier
     (email and password managed by Firebase directly)
         - username: String
         - hostname: String
         - paid: Bool
         - events
             - identifier: true
             - identifier: true
 
 Locations
     - identifier
        - g:  (geohash--String)
        - l
             - 0:  (latitude--Double)
             - 1:  (longitude--Double)
        - eventIdentifier: String
 
 
 
 
 */





/*
 backup of Firebase Database rules
 as they currently stand at Mon 8 Aug 11:30am
 
 {
 "rules": {
 "Events": {
 ".read" : true,
 ".write" : true
 },
 "Users": {
 ".read" : true,
 ".write" : true
 },
 "Locations": {
 ".read": true,
 ".write": true,
 ".indexOn": "g",
 "geofire": {
 },
 }
 }
 }
*/
